FROM python:3.11-slim

RUN pip install poetry==1.8.2

WORKDIR /chatops_udv/gigachat_api

COPY pyproject.toml poetry.lock ./
RUN touch README.md

RUN poetry install --no-root

COPY . .

CMD ["poetry", "run", "python", "-m", "main"]
