FROM python:3.11-slim

WORKDIR /chatops_udv/gigachat_api

RUN pip install poetry==1.8.2

COPY pyproject.toml poetry.lock ./
RUN touch README.md

ARG INSTALL_DEV=false
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --without dev ; fi"

RUN poetry run python -m spacy download ru_core_news_sm

COPY . .

CMD ["poetry", "run", "python", "-m", "main"]
